version: "3.9"

services:
  db:
    image: postgres:15
    container_name: express_db
    environment:
      POSTGRES_DB: express_sale_db
      POSTGRES_USER: express_sale_user
      POSTGRES_PASSWORD: express_sale_mdp
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U express_sale_user -d express_sale_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: express_backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env.docker  # 👈 AJOUTEZ CETTE LIGNE
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: express_sale_db
      DB_USERNAME: express_sale_user
      DB_PASSWORD: express_sale_mdp
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - backend_storage:/var/www/storage
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: express_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  pgdata:
  backend_storage: